version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    versioning-strategy: 'increase'
    groups:
      prod-deps:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      dev-deps:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: 'ci'
      include: 'scope'
